apiVersion: v1
kind: Service
metadata:
  name: site-lb2
  labels:
    app: my-webapp2
spec:
  type: LoadBalancer
  selector:
    app: my-webapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80