apiVersion: v1
kind: Service
metadata:
  name: site-lb
  labels:
    app: my-webapp
spec:
  type: LoadBalancer
  selector:
    app: my-webapp    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
