apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp2
  labels:
    app: my-webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp2
  template:
    metadata:
      labels:
        app: my-webapp2
    spec:
      containers:
        - name: my-webapp2
          image: bodya078/site2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"